### ISSUE TITLE
Should io-kit be published?

### ISSUE THREAD

**Issue by carlosmn** [jtakakura/io-kit-rs#5]
Hello, I was using io-kit-sys from crates.io and trying to interface with core-foundation's somewhat higher-level mechanics manually in my code, but then I was browsing this repository and noticed there is a higher-level set of bindings too, but they're not published.

Is the intention that it should also be available via crate?

Thanks.

**Comment by jtakakura** [comment]
At first, I planned to implement io-kit as io-kit-sys wrapper like core-foundation.
But currently, it's stopped because I don't have enough time.
